"""
events.py -- Constants for EventBus event types.
"""

# Tick/Scrape Events
TICK = "TICK"
SIGNAL = "SIGNAL"

# Order Lifecycle Events
ORDER_SUBMITTED = "ORDER_SUBMITTED"
ORDER_FILLED = "ORDER_FILLED"
ORDER_REJECTED = "ORDER_REJECTED"
ORDER_CANCELLED = "ORDER_CANCELLED"

# Position & Trade Events
POSITION_UPDATE = "POSITION_UPDATE"
TRADE_CLOSED = "TRADE_CLOSED"

# Account Events
ACCOUNT_SNAPSHOT = "ACCOUNT_SNAPSHOT"

# Session & System Events
SESSION_STATUS = "SESSION_STATUS"
REPLAY_PROGRESS = "REPLAY_PROGRESS"
ALERT_TRIGGERED = "ALERT_TRIGGERED"
